# Generated by Django 4.2.16 on 2024-10-05 06:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_question_questionpaper_choice_answersheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='answers',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='question',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.question'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='selected_choice',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='exam.choice'),
        ),
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('math', 'Math'), ('science', 'Science'), ('geography', 'Geography')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
