# Generated by Django 4.2.16 on 2024-10-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_alter_question_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='audio',
        ),
        migrations.RemoveField(
            model_name='question',
            name='image',
        ),
        migrations.RemoveField(
            model_name='question',
            name='video',
        ),
        migrations.AddField(
            model_name='choice',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='media_files/'),
        ),
        migrations.AddField(
            model_name='choice',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='question_media/'),
        ),
        migrations.AddField(
            model_name='question',
            name='media_type',
            field=models.CharField(blank=True, choices=[('image', 'Image'), ('video', 'Video'), ('audio', 'Audio')], max_length=10, null=True),
        ),
    ]
