# Generated by Django 4.2.16 on 2024-10-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_remove_question_audio_remove_question_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
