# Generated by Django 4.2.16 on 2025-03-10 03:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_questionpaper_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionpaper',
            name='duration',
            field=models.IntegerField(default=30, help_text='Duration of the test in minutes'),
        ),
        migrations.CreateModel(
            name='AssignedQuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
                ('question_paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.questionpaper')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
