# Generated by Django 4.2.16 on 2024-10-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='option_images/'),
        ),
        migrations.AddField(
            model_name='option',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='option_videos/'),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/'),
        ),
        migrations.AddField(
            model_name='question',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='question_videos/'),
        ),
    ]
